'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MAINSERVER\SQL2012;Initial Catalog=HRMS;User ID=sa;Password=P@ssw0rd")>  _
        Public ReadOnly Property HRMSConnectionString() As String
            Get
                Return CType(Me("HRMSConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LocX() As Integer
            Get
                Return CType(Me("LocX"),Integer)
            End Get
            Set
                Me("LocX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LocY() As Integer
            Get
                Return CType(Me("LocY"),Integer)
            End Get
            Set
                Me("LocY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("600")>  _
        Public Property SizeX() As Integer
            Get
                Return CType(Me("SizeX"),Integer)
            End Get
            Set
                Me("SizeX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("600")>  _
        Public Property SizeY() As Integer
            Get
                Return CType(Me("SizeY"),Integer)
            End Get
            Set
                Me("SizeY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property FormBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("FormBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("FormBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PanelColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("PanelColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("PanelColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Username() As String
            Get
                Return CType(Me("Username"),String)
            End Get
            Set
                Me("Username") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Password() As String
            Get
                Return CType(Me("Password"),String)
            End Get
            Set
                Me("Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Note() As String
            Get
                Return CType(Me("Note"),String)
            End Get
            Set
                Me("Note") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255, 255, 20")>  _
        Public Property YellowStickyNote() As Global.System.Drawing.Color
            Get
                Return CType(Me("YellowStickyNote"),Global.System.Drawing.Color)
            End Get
            Set
                Me("YellowStickyNote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255, 255, 137")>  _
        Public Property YellowLightStickyNote() As Global.System.Drawing.Color
            Get
                Return CType(Me("YellowLightStickyNote"),Global.System.Drawing.Color)
            End Get
            Set
                Me("YellowLightStickyNote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("38, 201, 222")>  _
        Public Property BlueStickyNote() As Global.System.Drawing.Color
            Get
                Return CType(Me("BlueStickyNote"),Global.System.Drawing.Color)
            End Get
            Set
                Me("BlueStickyNote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("140, 226, 238")>  _
        Public Property BlueLightStickyNote() As Global.System.Drawing.Color
            Get
                Return CType(Me("BlueLightStickyNote"),Global.System.Drawing.Color)
            End Get
            Set
                Me("BlueLightStickyNote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("154, 219, 42")>  _
        Public Property GreenStickyNote() As Global.System.Drawing.Color
            Get
                Return CType(Me("GreenStickyNote"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GreenStickyNote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("194, 233, 126")>  _
        Public Property GreenLightStickyNote() As Global.System.Drawing.Color
            Get
                Return CType(Me("GreenLightStickyNote"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GreenLightStickyNote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("222, 38, 201")>  _
        Public Property PinkStickyNote() As Global.System.Drawing.Color
            Get
                Return CType(Me("PinkStickyNote"),Global.System.Drawing.Color)
            End Get
            Set
                Me("PinkStickyNote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("238, 140, 226")>  _
        Public Property PinkLightStickyNote() As Global.System.Drawing.Color
            Get
                Return CType(Me("PinkLightStickyNote"),Global.System.Drawing.Color)
            End Get
            Set
                Me("PinkLightStickyNote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsOpenMailPanel() As Boolean
            Get
                Return CType(Me("IsOpenMailPanel"),Boolean)
            End Get
            Set
                Me("IsOpenMailPanel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsOpenCalendarPanel() As Boolean
            Get
                Return CType(Me("IsOpenCalendarPanel"),Boolean)
            End Get
            Set
                Me("IsOpenCalendarPanel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsOpenTasksPanel() As Boolean
            Get
                Return CType(Me("IsOpenTasksPanel"),Boolean)
            End Get
            Set
                Me("IsOpenTasksPanel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsOpenNotesPanel() As Boolean
            Get
                Return CType(Me("IsOpenNotesPanel"),Boolean)
            End Get
            Set
                Me("IsOpenNotesPanel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsOpenFoldersPanel() As Boolean
            Get
                Return CType(Me("IsOpenFoldersPanel"),Boolean)
            End Get
            Set
                Me("IsOpenFoldersPanel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NavIsHided() As Boolean
            Get
                Return CType(Me("NavIsHided"),Boolean)
            End Get
            Set
                Me("NavIsHided") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MAINSERVER\SQL2012;Initial Catalog=Email;Persist Security Info=True;U"& _ 
            "ser ID=sa;Password=P@ssw0rd")>  _
        Public ReadOnly Property EmailConnectionString() As String
            Get
                Return CType(Me("EmailConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Emailhostname() As String
            Get
                Return CType(Me("Emailhostname"),String)
            End Get
            Set
                Me("Emailhostname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property EmailPop3PortNbr() As Integer
            Get
                Return CType(Me("EmailPop3PortNbr"),Integer)
            End Get
            Set
                Me("EmailPop3PortNbr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EmailType() As String
            Get
                Return CType(Me("EmailType"),String)
            End Get
            Set
                Me("EmailType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EmailInteractionType() As String
            Get
                Return CType(Me("EmailInteractionType"),String)
            End Get
            Set
                Me("EmailInteractionType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EmailAutenticationType() As String
            Get
                Return CType(Me("EmailAutenticationType"),String)
            End Get
            Set
                Me("EmailAutenticationType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EmailUsername() As String
            Get
                Return CType(Me("EmailUsername"),String)
            End Get
            Set
                Me("EmailUsername") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EmailLogin() As String
            Get
                Return CType(Me("EmailLogin"),String)
            End Get
            Set
                Me("EmailLogin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EmailPassword() As String
            Get
                Return CType(Me("EmailPassword"),String)
            End Get
            Set
                Me("EmailPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SignedIn() As Boolean
            Get
                Return CType(Me("SignedIn"),Boolean)
            End Get
            Set
                Me("SignedIn") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=Email;Integrated Security=True")>  _
        Public ReadOnly Property EmailConnectionString1() As String
            Get
                Return CType(Me("EmailConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LastFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("LastFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("LastFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EmailOtherhostname() As String
            Get
                Return CType(Me("EmailOtherhostname"),String)
            End Get
            Set
                Me("EmailOtherhostname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property EmailSMTPPortNbr() As Integer
            Get
                Return CType(Me("EmailSMTPPortNbr"),Integer)
            End Get
            Set
                Me("EmailSMTPPortNbr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SelectedAccount() As String
            Get
                Return CType(Me("SelectedAccount"),String)
            End Get
            Set
                Me("SelectedAccount") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=TasksDB;Integrated Security=True")>  _
        Public ReadOnly Property TasksDBConnectionString() As String
            Get
                Return CType(Me("TasksDBConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=NotesDB;Integrated Security=True")>  _
        Public ReadOnly Property NotesDBConnectionString() As String
            Get
                Return CType(Me("NotesDBConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=HRMS;Integrated Security=True")>  _
        Public ReadOnly Property HRMSConnectionString1() As String
            Get
                Return CType(Me("HRMSConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-1O6SC07\SQLSERVER2012;Initial Catalog=HRMS;Integrated Securit"& _ 
            "y=True")>  _
        Public ReadOnly Property HRMSConnectionString2() As String
            Get
                Return CType(Me("HRMSConnectionString2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-BL68VM2\SQLSERVER2012;Initial Catalog=HRMS;Integrated Securit"& _ 
            "y=True")>  _
        Public ReadOnly Property HRMSConnectionString3() As String
            Get
                Return CType(Me("HRMSConnectionString3"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.HR.My.MySettings
            Get
                Return Global.HR.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
